# SPDX-License-Identifier: GPL-3.0-or-later

if(NOT DEFINED THOTHPAD_COPY_SOURCE OR NOT DEFINED THOTHPAD_COPY_DESTINATION)
    message(FATAL_ERROR "THOTHPAD_COPY_SOURCE and THOTHPAD_COPY_DESTINATION are required")
endif()

if(IS_DIRECTORY "${THOTHPAD_COPY_SOURCE}")
    file(MAKE_DIRECTORY "${THOTHPAD_COPY_DESTINATION}")
    file(COPY "${THOTHPAD_COPY_SOURCE}/" DESTINATION "${THOTHPAD_COPY_DESTINATION}")
endif()
